### ISSUE TITLE
wordpress-openid does not publish openid provider via XRDS

### ISSUE THREAD

**Issue by simonwgill** [diso/wordpress-openid#13] opened 2012-03-26 19:54 UTC
I've been using a single-author wordpress install as my OpenID for a while. After I upgraded to 3.3, things went wrong.

I've isolated this code block from lines 53-55 which is ending the function before adding the provider services. For my example openid of "http://www.patternwebsolutions.com/" $path is always going to be "/" where $script is "/index.php/openid/server".

    if ($path != $script && !is_admin()) {
      return $xrds;
    }

Two questions. What is this block checking for? And why are you checking that a logged-in admin user is requesting the xrds document?

I've commented it out for now, and it's pushing out the correct xrds elements. Now, I just have to figure out why wordpress is giving me an intermittent 404 error. I suspect my rewrite rules are doing something screwy.

**Comment by pfefferle** [comment] 2015-07-22 21:32
Is this still a problem? I couldn't reproduce it.

**Comment by pfefferle** [comment] 2015-08-10 21:01
I will close this, if it still exists, please reopen it.

**Closed by pfefferle** 2015-08-10 21:01 UTC
